CREATE TABLE tb_address
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street       VARCHAR(255),
    number       INTEGER,
    complement   VARCHAR(255),
    neighborhood VARCHAR(255),
    city         VARCHAR(255),
    state        VARCHAR(255),
    zip_code     BIGINT,
    CONSTRAINT pk_tb_address PRIMARY KEY (id)
);

CREATE TABLE tb_event
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    description  TEXT,
    event_date   date,
    guest_number INTEGER,
    address_id   BIGINT,
    user_id      BIGINT,
    CONSTRAINT pk_tb_event PRIMARY KEY (id)
);

CREATE TABLE tb_guest
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    email     VARCHAR(255),
    confirmed BOOLEAN,
    table_id  BIGINT,
    CONSTRAINT pk_tb_guest PRIMARY KEY (id)
);

CREATE TABLE tb_password_recover
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token      VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    expiration TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_tb_password_recover PRIMARY KEY (id)
);

CREATE TABLE tb_role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority VARCHAR(255),
    CONSTRAINT pk_tb_role PRIMARY KEY (id)
);

CREATE TABLE tb_table_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  TEXT,
    guest_number INTEGER,
    event_id     BIGINT,
    CONSTRAINT pk_tb_table_entity PRIMARY KEY (id)
);

CREATE TABLE tb_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

CREATE TABLE tb_user_role
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_user_role PRIMARY KEY (role_id, user_id)
);

ALTER TABLE tb_event
    ADD CONSTRAINT uc_tb_event_address UNIQUE (address_id);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);

ALTER TABLE tb_event
    ADD CONSTRAINT FK_TB_EVENT_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES tb_address (id);

ALTER TABLE tb_event
    ADD CONSTRAINT FK_TB_EVENT_ON_USER FOREIGN KEY (user_id) REFERENCES tb_user (id);

ALTER TABLE tb_guest
    ADD CONSTRAINT FK_TB_GUEST_ON_TABLE FOREIGN KEY (table_id) REFERENCES tb_table_entity (id);

ALTER TABLE tb_table_entity
    ADD CONSTRAINT FK_TB_TABLE_ENTITY_ON_EVENT FOREIGN KEY (event_id) REFERENCES tb_event (id);

ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_tbuserol_on_role FOREIGN KEY (role_id) REFERENCES tb_role (id);

ALTER TABLE tb_user_role
    ADD CONSTRAINT fk_tbuserol_on_user FOREIGN KEY (user_id) REFERENCES tb_user (id);